apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: back
  template:
    metadata:
      labels:
        app: dockercoins
        tier: back
    spec:
      containers:
        - name: rng
          image: salahkefi/rng
        - name: hasher
          image: salahkefi/hasher
        - name: worker
          image: salahkefi/worker
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: dockercoins
      tier: db
  template:
    metadata:
      labels:
        app: dockercoins
        tier: db
    spec:
      containers:
        - name: redis
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP
  selector:
    app: dockercoins
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: dockercoins
      tier: front
  template:
    metadata:
      labels:
        app: dockercoins
        tier: front
    spec:
      containers:
        - name: webui
          image: salahkefi/webui
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
  selector:
    app: dockercoins
    tier: front
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
 